### ISSUE TITLE
.pem & Cert

### ISSUE THREAD

**Issue by isshiimwe** [getpinga/fossbilling-epp-rfc#2]
How do i get these

**Comment by getpinga** [comment]
You need to get them from your registry. If they do not give such, use this:

To create test certificates (cert.pem and key.pem), if the registry does not have mandatory SSL certificates, you can use:
openssl genrsa -out key.pem 2048
openssl req -new -x509 -key key.pem -out cert.pem -days 365

**Comment by isshiimwe** [comment]
With only these COCCA Info will I be able to use your extension?
![WhatsApp Image 2023-03-08 at 13 20 26 (1)](https://user-images.githubusercontent.com/122705379/223714385-009564ad-ac34-4ad7-bb35-797937da6fbf.jpeg)

**Comment by getpinga** [comment]
Yes, you will need epp server, username and password. If you can't find the epp server, ask at registry or send me an email to tk@getpinga.com with the extensions you use for Cocca and I'll find the EPP servers.

Regarding the certificates, you can use the test ones generated with the commands I sent before. Cocca is not strict with the SSL.

**Comment by isshiimwe** [comment]
what do we add on Registrar Prefix, don't seem to be found within those details I have  ![Screenshot (1)](https://user-images.githubusercontent.com/122705379/223788684-d8e0c44a-47e0-40d1-a198-bf9d195d2376.png)

**Comment by isshiimwe** [comment]
Normally I use Let's Encrypt to generate SSL

**Comment by getpinga** [comment]
Registrar prefix can be some short string that identifies your company, for example if name is EXAMPLE, it could be EXA.

Let's Encrypt SSL is also ok, just make sure you put the right files in the plugin directory.
