### ISSUE TITLE
Configuration details

### ISSUE THREAD

**Issue by salhaansallu** [getpinga/fossbilling-epp-rfc#6]
Hi,

I'm confused what are the configuration details I need to add in order to add a godaddy reseller account.
Please can anyone can help me do it.

EPP Server Username
EPP Server Password
EPP Server Host
EPP Server Port
Registrar Prefix
SSL Certificate Path

**Comment by getpinga** [comment]
Hello, As far as I know, Godaddy does not provide EPP for resellers. And this module is for EPP based servers only. But please check with them.
