### ISSUE TITLE
Cannot connect to server 'ip': (namingo registry epp)

### ISSUE THREAD

**Issue by wvro-org** [getpinga/fossbilling-epp-rfc#7]
When in fossbilling 
In client and/or admin
Interface trying to create domain
test.com.test (for example)
gives error 
Cannot connect to server 'ip':
To my mind this problem is with epp
However in registry (namingo) in /opt/registry/epp/config.php
ip and port(700) Are all OK
Password and user are all OK 
and certs are all OK 
and database OK to
.....

**Comment by wvro-org** [comment]
update 
tried using epp client 
gives error
pepper> connect
*** Connecting to ip...
*** Error: Unable to connect: Error connecting: Connection to IP:700 failed: SSL connect attempt failed error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed
smth with ssl certs

**Comment by getpinga** [comment]
Thanks, investigating.

**Comment by wvro-org** [comment]
update 
invsetigated too
still form example.com/admin/order/new  givese error 
Cannot connect to server 'IP': (9999) 
to my mind issure is  in fossbilling epp not on namingo registry side

**Comment by wvro-org** [comment]
Update
Now the issue is on fossbilling/fossbilling-epp-rfc side
Fixed connection issue.
Changed fossbilling-epp-rfc/epp.php lines    98...
            
                'ssl_ca' => array('text', array(
                    'label' => 'SSL CA Path',
                    'required' => false, to true 
Worked for me when spinned up test ca authority (luckily had one already)


Now the same form gives error 

Call to a member function getLocked() on array at /var/www/modules/Servicedomain/Service.php:339

**Comment by wvro-org** [comment]
fixed errorr at Call to a member function getLocked() on array at /var/www/modules/Servicedomain/Service.php:339 and some more lines thanks to help of phind ai
`    protected function syncWhois(\Model_ServiceDomain $model, \Model_ClientOrder $order)
    {
        // @adapterAction
        [$domain, $adapter] = $this->_getD($model);

        // update whois
        $whois = $adapter->getDomainDetails($domain);

      //  $locked = $whois->getLocked();
        //if ($locked !== null) {
          //  $model->locked = $locked;
       // }
           $locked = $whois['locked'] ?? null;
           if ($locked !== null) {
           $model->locked = $locked;
           }

        // sync whois
        //$contact = $whois->getContactRegistrar();

       // $model->contact_first_name = $contact->getFirstName();
       // $model->contact_last_name = $contact->getLastName();
      //  $model->contact_email = $contact->getEmail();
      //  $model->contact_company = $contact->getCompany();
       // $model->contact_address1 = $contact->getAddress1();
       // $model->contact_address2 = $contact->getAddress2();
       // $model->contact_country = $contact->getCountry();
       // $model->contact_city = $contact->getCity();
       // $model->contact_state = $contact->getState();
       // $model->contact_postcode = $contact->getZip();
       // $model->contact_phone_cc = $contact->getTelCc();
       // $model->contact_phone = $contact->getTel();

       $contact = $whois['contact_registrar'] ?? null;
       if ($contact !== null) {
           $model->contact_first_name = $contact['first_name'] ?? null;
           $model->contact_last_name = $contact['last_name'] ?? null;
           $model->contact_email = $contact['email'] ?? null;
           $model->contact_company = $contact['company'] ?? null;
           $model->contact_address1 = $contact['address1'] ?? null;
           $model->contact_address2 = $contact['address2'] ?? null;
           $model->contact_country = $contact['country'] ?? null;
           $model->contact_city = $contact['city'] ?? null;
           $model->contact_state = $contact['state'] ?? null;
           $model->contact_postcode = $contact['postcode'] ?? null;
           $model->contact_phone_cc = $contact['phone_cc'] ?? null;
           $model->contact_phone = $contact['phone'] ?? null;
       }


        $model->details = serialize($whois);
        //$model->expires_at = date('Y-m-d H:i:s', $whois->getExpirationTime());
        $model->expires_at = isset($whois['expiration_time']) ? date('Y-m-d H:i:s', $whois['expiration_time']) : null;
        //$model->registered_at = date('Y-m-d H:i:s', $whois->getRegistrationTime());
        $model->registered_at = isset($whois['registration_time']) ? date('Y-m-d H:i:s', $whois['registration_time']) : null;
       
        $model->updated_at = date('Y-m-d H:i:s');

        $this->di['db']->store($model);
    }` haven't yet tested for other errors ....

**Comment by anantsparrow** [comment]
@wvro-org hi there, i am getting the same error, can you help me out?

**Comment by getpinga** [comment]
Please try now 0.9.2, it is supposed to fix those issues. Check also the troubleshooting section in the readme and make sure all steps are done.
